version: '3'
services:
  # Postgres
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  app:
    build: .
    volumes:
      - staticfiles:/app/static
    environment:
      - PRODUCTION=True
      - DJANGO_SECRET_KEY=asdfmovie
    ports:
      - "8080:8080"
  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/static
    ports:
      - "80:80"

volumes:
  staticfiles:
